# Generated by Django 5.2.10 on 2026-01-22 20:42

import oscar.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0006_auto_20181115_1953"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="code",
            field=oscar.models.fields.NullCharField(
                max_length=255, unique=True, verbose_name="Code"
            ),
        ),
    ]
