# Generated by CodeSpeak from spec file: src/oscar/apps/order/line_reports.spec.md
# Modifying this file manually is DISCOURAGED.
# CodeSpeak will try to preserve manual changes, but it's not guaranteed.

from django.utils.translation import gettext_lazy as _

from oscar.core.loading import get_class, get_model

ReportGenerator = get_class("dashboard.reports.reports", "ReportGenerator")
ReportCSVFormatter = get_class("dashboard.reports.reports", "ReportCSVFormatter")
ReportHTMLFormatter = get_class("dashboard.reports.reports", "ReportHTMLFormatter")
Line = get_model("order", "Line")


class OrderLineReportCSVFormatter(ReportCSVFormatter):
    filename_template = "order-lines-%s-to-%s.csv"

    def generate_csv(self, response, lines):
        writer = self.get_csv_writer(response)
        header_row = [
            _("Order number"),
            _("SKU"),
            _("Product title"),
            _("Quantity"),
            _("Line price (incl. tax)"),
            _("Partner name"),
        ]
        writer.writerow(header_row)
        for line in lines:
            row = [
                line.order.number,
                line.partner_sku or line.upc or "-",
                line.title,
                line.quantity,
                line.line_price_incl_tax,
                line.partner_name or "-",
            ]
            writer.writerow(row)

    def filename(self, **kwargs):
        return self.filename_template % (kwargs["start_date"], kwargs["end_date"])


class OrderLineReportHTMLFormatter(ReportHTMLFormatter):
    filename_template = "oscar/dashboard/reports/partials/order_line_report.html"


class OrderLineReportGenerator(ReportGenerator):
    code = "order_line_report"
    description = _("Order line items")
    date_range_field_name = "order__date_placed"
    model_class = Line

    formatters = {
        "CSV_formatter": OrderLineReportCSVFormatter,
        "HTML_formatter": OrderLineReportHTMLFormatter,
    }

    def get_queryset(self):
        """
        Return queryset with order relationship selected to avoid N+1 queries
        """
        return (
            super()
            .get_queryset()
            .select_related("order", "product", "partner")
            .order_by("order__date_placed", "order__number", "id")
        )

    def generate(self):
        additional_data = {"start_date": self.start_date, "end_date": self.end_date}
        return self.formatter.generate_response(self.queryset, **additional_data)

    def is_available_to(self, user):
        return user.is_staff