from setuptools import setup

from oscar import get_version

version = get_version()

setup(name='django-oscar',
      version=version.replace(' ', '-'),
      url='https://github.com/tangentlabs/django-oscar',
      author="Tangent Labs",
      author_email="david.winterbottom@tangentlabs.co.uk",
      description="A domain-driven ecommerce framework for Django 1.3",
      long_description=open('README.rst').read(),
      license='LICENSE',
      packages=['oscar',
                'oscar.core',
                'oscar.core.logging',
                'oscar.test',
                'oscar.views',
                'oscar.templatetags',
                'oscar.apps',
                'oscar.apps.order_management',
                'oscar.apps.promotions',
                'oscar.apps.promotions.templatetags',
                'oscar.apps.reports',
                'oscar.apps.discount',
                'oscar.apps.search',
                'oscar.apps.shipping',
                'oscar.apps.product',
                'oscar.apps.product.management',
                'oscar.apps.product.management.commands',
                'oscar.apps.product.reviews',
                'oscar.apps.basket',
                'oscar.apps.basket.templatetags',
                'oscar.apps.address',
                'oscar.apps.dynamic_images',
                'oscar.apps.dynamic_images.templatetags',
                'oscar.apps.payment',
                'oscar.apps.payment.datacash',
                'oscar.apps.payment.tests',
                'oscar.apps.offer',
                'oscar.apps.partner',
                'oscar.apps.partner.management',
                'oscar.apps.partner.management.commands',
                'oscar.apps.partner.tests',
                'oscar.apps.order',
                'oscar.apps.checkout',
                'oscar.apps.customer',
                'oscar.apps.customer.templatetags',
                'oscar.apps.analytics',
                'oscar.apps.analytics.management',
                'oscar.apps.analytics.management.commands',
                'oscar.forms'],
      package_data={'oscar': ['templates/basket/*.html',
                              'templates/checkout/*.html',
                              'templates/customer/*.html',
                              'templates/customer/history/*.html',
                              'templates/order_management/*.html',
                              'templates/product/*.html',
                              'templates/promotion/*.html',
                              'templates/reports/*.html',
                              'templates/reviews/*.html',
                              'templates/search/*.html',
                              'templates/search/indexes/*/*.txt'],
                    'oscar.apps.search': ['fixtures/*'],
                    'oscar.apps.shipping': ['fixtures/*'],
                    'oscar.apps.product.reviews': ['fixtures/*'],
                    'oscar.apps.product': ['fixtures/*'],
                    'oscar.apps.address': ['fixtures/*'],
                    'oscar.apps.dynamic_images': ['test_fixtures/*'],
                    'oscar.apps.offer': ['fixtures/*'],
                    'oscar.apps.partner': ['fixtures/*'],
                    'oscar.apps.order': ['fixtures/*']},
      install_requires=[
          'django-haystack>=1.2.0',
          'django-treebeard>=1.6.1',
          'sorl-thumbnail>=11.05.1'],
      # See http://pypi.python.org/pypi?%3Aaction=list_classifiers
      classifiers=['Development Status :: 3 - Alpha',
                   'Environment :: Web Environment',
                   'Framework :: Django',
                   'Intended Audience :: Developers',
                   'License :: OSI Approved :: BSD License',
                   'Operating System :: Unix',
                   'Programming Language :: Python']
      )
