# Generated by Django 3.2.11 on 2022-01-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0001_initial'),
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangeproductfileupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.product'),
        ),
        migrations.AddField(
            model_name='rangeproduct',
            name='range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.range'),
        ),
        migrations.AddField(
            model_name='range',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='catalogue.ProductClass', verbose_name='Product Types'),
        ),
        migrations.AddField(
            model_name='range',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, related_name='excludes', to='catalogue.Product', verbose_name='Excluded Products'),
        ),
        migrations.AddField(
            model_name='range',
            name='included_categories',
            field=models.ManyToManyField(blank=True, related_name='includes', to='catalogue.Category', verbose_name='Included Categories'),
        ),
        migrations.AddField(
            model_name='range',
            name='included_products',
            field=models.ManyToManyField(blank=True, related_name='includes', through='offer.RangeProduct', to='catalogue.Product', verbose_name='Included Products'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offer.benefit', verbose_name='Benefit'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='combinations',
            field=models.ManyToManyField(blank=True, help_text='Select other non-exclusive offers that this offer can be combined with on the same items', limit_choices_to={'exclusive': False}, related_name='in_combination', to='offer.ConditionalOffer'),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offer.condition', verbose_name='Condition'),
        ),
        migrations.AddField(
            model_name='condition',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.range', verbose_name='Range'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.range', verbose_name='Range'),
        ),
        migrations.CreateModel(
            name='AbsoluteDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Absolute discount benefit',
                'verbose_name_plural': 'Absolute discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='CountCondition',
            fields=[
            ],
            options={
                'verbose_name': 'Count condition',
                'verbose_name_plural': 'Count conditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
        migrations.CreateModel(
            name='CoverageCondition',
            fields=[
            ],
            options={
                'verbose_name': 'Coverage Condition',
                'verbose_name_plural': 'Coverage Conditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
        migrations.CreateModel(
            name='FixedPriceBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed price benefit',
                'verbose_name_plural': 'Fixed price benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='MultibuyDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Multibuy discount benefit',
                'verbose_name_plural': 'Multibuy discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='PercentageDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Percentage discount benefit',
                'verbose_name_plural': 'Percentage discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='ShippingBenefit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.benefit',),
        ),
        migrations.CreateModel(
            name='ValueCondition',
            fields=[
            ],
            options={
                'verbose_name': 'Value condition',
                'verbose_name_plural': 'Value conditions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.condition',),
        ),
        migrations.AlterUniqueTogether(
            name='rangeproduct',
            unique_together={('range', 'product')},
        ),
        migrations.CreateModel(
            name='ShippingAbsoluteDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Shipping absolute discount benefit',
                'verbose_name_plural': 'Shipping absolute discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.shippingbenefit',),
        ),
        migrations.CreateModel(
            name='ShippingFixedPriceBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Fixed price shipping benefit',
                'verbose_name_plural': 'Fixed price shipping benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.shippingbenefit',),
        ),
        migrations.CreateModel(
            name='ShippingPercentageDiscountBenefit',
            fields=[
            ],
            options={
                'verbose_name': 'Shipping percentage discount benefit',
                'verbose_name_plural': 'Shipping percentage discount benefits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('offer.shippingbenefit',),
        ),
    ]
