# Generated by Django 2.1.7 on 2019-03-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='combinations',
            field=models.ManyToManyField(blank=True, help_text='Select offers this offer can be combined with on the same items', related_name='in_combination', to='offer.ConditionalOffer'),
        ),
    ]
