# Generated by Django 3.2.15 on 2022-08-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_rangeproductexcludedfileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangeproductexcludedfileupload',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
