# Generated by Django 4.2.16 on 2024-10-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0006_auto_20200724_0909"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Name"
                    ),
                ),
                ("location", models.URLField(blank=True, max_length=300, null=True)),
                ("coordinates", models.JSONField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "abstractarea_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="partner.abstractarea",
                    ),
                ),
            ],
            bases=("partner.abstractarea",),
        ),
    ]
