# Generated by Django 4.2.16 on 2024-10-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0007_abstractarea_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="areas",
            field=models.ManyToManyField(
                blank=True,
                related_name="partners",
                to="partner.abstractarea",
                verbose_name="Areas",
            ),
        ),
    ]
