# Generated by Django 4.2.16 on 2024-10-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0008_partner_areas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="areas",
        ),
    ]
