# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightbased',
            name='code',
        ),
        migrations.AlterField(
            model_name='orderanditemcharges',
            name='countries',
            field=models.ManyToManyField(blank=True, to='address.Country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='weightbased',
            name='countries',
            field=models.ManyToManyField(blank=True, to='address.Country', verbose_name='Countries'),
        ),
    ]
