# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import oscar.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, storage=oscar.core.storages.DocumentsStorage(), upload_to='invoices/%Y/%m/', verbose_name='Document'),
        ),
    ]
