# Generated by Django 4.2.9 on 2024-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_orderlinediscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="num_allocated",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number allocated"
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="restocked",
            field=models.BooleanField(default=False),
        ),
    ]
