# Generated by Django 5.1.4 on 2025-01-20 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_line_num_allocated'),
        ('user', '0007_remove_city_name_ar_remove_city_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='line4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='line4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.city', verbose_name='City'),
        ),
    ]
