# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20170601_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherset',
            name='count',
            field=models.IntegerField(verbose_name='Number of vouchers'),
        ),
    ]
