# Generated by Django 2.2 on 2020-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_line_date_updated'),
        ('voucher', '0008_auto_20200801_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='baskets',
            field=models.ManyToManyField(blank=True, to='basket.Basket', verbose_name='Baskets'),
        ),
    ]
