# Generated by Django 2.2 on 2020-10-22 13:49

from django.db import migrations


def swap_vouchers_and_baskets(apps, schema_editor):
    """
    Before deleting `vouchers` field from `Basket` model we should migrate all related
    baskets to `baskets` field of all related vouchers.
    """
    Basket = apps.get_model('basket', 'Basket')
    for basket in Basket.objects.filter(vouchers__isnull=False).iterator():
        for voucher in basket.vouchers.all():
            voucher.baskets.add(basket)


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_voucher_baskets'),
    ]

    operations = [
        migrations.RunPython(swap_vouchers_and_baskets),
    ]
