# Generated by Django 2.2 on 2020-10-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_swap_vouchers_and_baskets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='baskets',
            field=models.ManyToManyField(blank=True, related_name='vouchers', to='basket.Basket', verbose_name='Baskets'),
        ),
    ]
