# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20150807_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalert',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='Email'),
        ),
    ]
