# Generated by Django 3.1 on 2021-10-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200801_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productalert',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, unique=True, verbose_name='Key'),
        ),
    ]
