# Generated by Django 2.1.1 on 2018-09-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=64)),
                ('shop_tagline', models.CharField(max_length=256)),
                ('homepage_url', models.CharField(default='/', max_length=256)),
                ('use_less', models.BooleanField(default=False)),
                ('google_analytics_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Configuration',
                'abstract': False,
            },
        ),
    ]
