# Generated by Django 2.1.1 on 2018-09-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='dashboard_editor_plugins',
            field=models.CharField(default='link lists', max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='dashboard_editor_toolbar_layout',
            field=models.CharField(default='styleselect | bold italic blockquote | bullist numlist | link', max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shop_date_format',
            field=models.CharField(default='yy-mm-dd', max_length=32),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shop_date_picker_minute_step',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shop_datetime_format',
            field=models.CharField(default='yy-mm-dd hh:ii', max_length=32),
        ),
        migrations.AddField(
            model_name='configuration',
            name='shop_time_format',
            field=models.CharField(default='hh:ii', max_length=32),
        ),
    ]
