# Generated by Django 2.1.1 on 2018-09-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180914_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='dashboard_editor_context_menu',
            field=models.CharField(default='link', max_length=255),
        ),
    ]
