# Generated by Django 2.1.1 on 2018-09-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_configuration_dashboard_editor_context_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='dashboard_editor_menubar_layout',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='dashboard_editor_context_menu',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='dashboard_editor_plugins',
            field=models.CharField(blank=True, default='link lists', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='dashboard_editor_toolbar_layout',
            field=models.CharField(blank=True, default='styleselect | bold italic blockquote | bullist numlist | link', max_length=255),
        ),
    ]
