# Generated by Django 2.2 on 2020-10-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_line_date_updated'),
        ('voucher', '0010_swap_vouchers_and_baskets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='vouchers',
        ),
    ]
