# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonyms', models.CharField(help_text='Comma-separated list of synonyms, optionally mapped using "=>" to what they should be rewritten to.', max_length=255)),
            ],
        ),
    ]
