# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-22 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20170420_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(
                db_constraint=False,
                verbose_name='Product',
                related_name='images',
                to='catalogue.Product',
                on_delete=models.CASCADE),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(
                db_constraint=True,
                verbose_name='Product',
                related_name='images',
                to='catalogue.Product',
                on_delete=models.CASCADE),
        ),
    ]
