# Generated by Django 2.1.1 on 2018-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_product_is_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='This flag indicates if this product will be displayed or not', verbose_name='Is enabled?'),
        ),
    ]
