# Generated by Django 3.2.11 on 2022-01-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0023_auto_20210824_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='default',
            field=models.CharField(max_length=255, null=True, verbose_name='Default initial data'),
        ),
        migrations.AddField(
            model_name='option',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Compile show options in an ordered sequence', verbose_name='Sequence'),
        ),
    ]
