# Generated by Django 3.2.11 on 2022-01-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_auto_20220113_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='help_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='option',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Default initial data'),
        ),
    ]
