# Generated by Django 3.2.12 on 2022-03-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0024_predefined_product_options'),
        ('catalogue', '0025_attribute_code_uniquetogether_constraint'),
    ]

    operations = [
    ]
