# Generated by Django 3.2.11 on 2022-01-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0025_auto_20220113_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'True / False'), ('float', 'Float'), ('date', 'Date'), ('choice', 'Choice')], default='text', max_length=255, verbose_name='Type'),
        ),
    ]
