# Generated by Django 3.2.11 on 2022-01-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_alter_option_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices'),
        ),
    ]
