# Generated by Django 3.2.12 on 2022-03-14 22:07

from django.db import migrations, models


def regenerate_null_fields(apps, schema_editor):
    """
    Migrate charfield to empty string 
    """
    def regenerate_null_fields(apps, schema_editor):
        Category = apps.get_model('catalogue', 'Category')
        Category.objects.filter(meta_description__isnull=True).update(meta_description='')
        Category.objects.filter(meta_title__isnull=True).update(meta_title='')

        Product = apps.get_model('catalogue', 'Product')
        Product.objects.filter(meta_description__isnull=True).update(meta_description='')
        Product.objects.filter(meta_title__isnull=True).update(meta_title='')


        Option = apps.get_model('catalogue', 'Option')
        Option.objects.filter(help_text__isnull=True).update(help_text='')

        ProductAttributeValue = apps.get_model('catalogue', 'ProductAttributeValue')
        ProductAttributeValue.objects.filter(value_richtext__isnull=True).update(value_richtext='')
        ProductAttributeValue.objects.filter(value_text__isnull=True).update(value_text='')


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_predefined_product_options'),
    ]

    operations = [
        migrations.RunPython(regenerate_null_fields, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='option',
            name='help_text',
            field=models.CharField(blank=True, help_text='Help text shown to the user on the add to basket form', max_length=255, verbose_name='Help text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, verbose_name='Meta description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta title'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_richtext',
            field=models.TextField(blank=True, verbose_name='Richtext'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value_text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
