# Generated by Django 3.2.11 on 2022-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_option_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='choices',
            field=models.CharField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', max_length=1024, verbose_name='choices'),
        ),
    ]
