# Generated by Django 5.2.4 on 2025-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0031_productcategoryhierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_visible",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Show this category in the menu.",
                verbose_name="Is visible",
            ),
        ),
    ]
