# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 10:50
from __future__ import unicode_literals

from django.db import migrations


MODELS = (
    'communicationeventtype', 'email', 'notification', 'productalert'
)


def update_content_types(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='customer', model__in=MODELS).update(app_label='communication')


def reverse_content_types_update(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ContentType.objects.filter(app_label='communication', model__in=MODELS).update(app_label='customer')


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(update_content_types, reverse_code=reverse_content_types_update)
    ]
