# Generated by Django 2.0.13 on 2019-05-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20190430_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='category',
        ),
    ]
