# Generated by Django 2.0.13 on 2019-12-08 10:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False  # Needed for SQLite

    dependencies = [
        ('communication', '0004_auto_20191201_1034'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communicationeventtype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
    ]
