# Generated by Django 5.2.10 on 2026-01-30 09:47

import oscar.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_auto_20170429_0941"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="code",
            field=oscar.models.fields.NullCharField(
                max_length=255, unique=True, verbose_name="Code"
            ),
        ),
    ]
